@echo off
setlocal

set "CHEK_EDGE_ROOT=__EDGE_ROOT__"
set "EDGE_RUNTIME_PROFILE=__EDGE_RUNTIME_PROFILE__"
set "EDGE_CONTROL_ENABLED=__EDGE_CONTROL_ENABLED__"
set "EDGE_SIM_ENABLED=__EDGE_SIM_ENABLED__"
set "STACK_BIND_HOST=__STACK_BIND_HOST__"
set "STACK_CHECK_HOST=__STACK_BIND_HOST__"
set "STACK_PUBLIC_HOST=__STACK_PUBLIC_HOST__"

call "__TELEOP_STACK_CMD__" start --bind-host "__STACK_BIND_HOST__" --public-host "__STACK_PUBLIC_HOST__" __NO_SIM_FLAG__
exit /b %errorlevel%
